server:
  port: 8081

spring:
  application:
    name: sc-gateway-server
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    gateway:
      discovery:
        locator:
          enabled: false
          lowerCaseServiceId: true
      routes:
      - id: dynamic-route-a
        uri: lb://service-hi
        predicates:
          - Path=/route-a/**
        filters:
          - StripPrefix=1

      - id: dynamic-route-b
        uri: lb://service-hi
        predicates:
          - Path=/route-b/demo/**
        filters:
          - StripPrefix=2

      - id: service-hi
        uri: lb://service-hi
        predicates:
          - Path=/demo/**
        filters:
          - StripPrefix=1
          - RequestTime=true

logging:
  level:
    org.springframework.cloud.gateway: debug



